# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_deploy:
- R CMD INSTALL $PKG_TARBALL

deploy:
  provider: script
  script: Rscript -e "print('hello!')"
  on:
    branch: master
